- name: Setup Golang
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: get username
      become: false
      local_action: command whoami
      register: local_username
    - name: get latest golang filename
      shell: curl 'https://go.dev/dl/?mode=json' | jq -r '.[0].files[] | select(.filename|test("linux-amd64")).filename'
      register: golang_ver
    - name: Clean-up of golang directory
      file:
        state: absent
        path: /usr/local/go
    - name: Recreate golang directory
      file:
        state: directory
        path: /usr/local/go
    - name: Getting golang via wget
      get_url:
        url: https://go.dev/dl/{{golang_ver.stdout}}
        dest: /usr/local
    - name: Unpack golang stuff
      unarchive:  
        src: /usr/local/{{golang_ver.stdout}}
        dest: /usr/local
    - name: Remove golang package
      file:
        state: absent
        path: /usr/local/{{golang_ver.stdout}}
    - name: Add go binary files to local PATH environment variable
      lineinfile:
        dest: "/home/{{local_username.stdout}}/.bashrc"
        line: export PATH=$PATH:/usr/local/go/bin