- name: Install commonly used packages
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: install commonly used packages
      package:
        name:
          - jq
          - net-tools